---
name: Update cmd-fowarder-vppagent
on:
  push:
    branches:
      - master

jobs:
  update-cmd-forwarder-vppagent:
    name: Update cmd-forwarder-vppagent
    runs-on: ubuntu-latest
    if: github.repository == 'networkservicemesh/sdk-vppagent'
    steps:
      - uses: actions/checkout@v2
        with:
          repository: networkservicemesh/cmd-forwarder-vppagent
          token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.4
      - name: Update sdk-vppagent locally
        run: |
          GOPROXY=direct go get -u github.com/networkservicemesh/sdk-vppagent
          go mod tidy
          git diff
      - name: Push update to cmd-forwarder-vppagent
        run: |
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"
          git add go.mod go.sum
          git commit -s -m "Update go.mod and go.sum to latest version from networkservicemesh/sdk-vppagent@master"
          git checkout -b update/sdk-vppagent-gomod
          git push -f origin update/sdk-vppagent-gomod
